# Generated by Django 5.1.1 on 2024-09-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='shopping', max_length=100),
        ),
    ]
