# Generated by Django 5.1.1 on 2024-09-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='code',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='+254700000000', max_length=15),
        ),
    ]
