name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          DB_NAME: customerordersdb
          DB_USER: postgres
          DB_PASSWORD: Prisca99
        ports:
          - 5432:5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test
